// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQMtc_SW1TmNkj5flue5rX3TP-LaHbQE8',
    appId: '1:557441465698:web:c2d3c56290479cca1d403b',
    messagingSenderId: '557441465698',
    projectId: 'event-planner-3f077',
    authDomain: 'event-planner-3f077.firebaseapp.com',
    storageBucket: 'event-planner-3f077.firebasestorage.app',
    measurementId: 'G-90Q44D6XZX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiLtpM5FIya1U2kHSWI2i_M8ZQzdwn48Q',
    appId: '1:557441465698:ios:20195d19b22886ff1d403b',
    messagingSenderId: '557441465698',
    projectId: 'event-planner-3f077',
    storageBucket: 'event-planner-3f077.firebasestorage.app',
    iosBundleId: 'com.example.eventplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQMtc_SW1TmNkj5flue5rX3TP-LaHbQE8',
    appId: '1:557441465698:web:8331671cdece0b791d403b',
    messagingSenderId: '557441465698',
    projectId: 'event-planner-3f077',
    authDomain: 'event-planner-3f077.firebaseapp.com',
    storageBucket: 'event-planner-3f077.firebasestorage.app',
    measurementId: 'G-B86DNT44V9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiLtpM5FIya1U2kHSWI2i_M8ZQzdwn48Q',
    appId: '1:557441465698:ios:20195d19b22886ff1d403b',
    messagingSenderId: '557441465698',
    projectId: 'event-planner-3f077',
    storageBucket: 'event-planner-3f077.firebasestorage.app',
    iosBundleId: 'com.example.eventplanner',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHQPxoDGVs_nSV-l0WnoXTKhaHlEWY9KE',
    appId: '1:557441465698:android:244fb2ec4dd59c8a1d403b',
    messagingSenderId: '557441465698',
    projectId: 'event-planner-3f077',
    storageBucket: 'event-planner-3f077.firebasestorage.app',
  );

}